Repository dev-memento/memento-iOS, pull requests merged in 2025-08, with the labels that each got.

#41 [Refactor] #39 - AddToDo View, ViewModel / SegmentedMenuView 개선
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/PriorityLabel.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarView.swift
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoHeaderView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoPriorityView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoTextView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Model/SegmentedMenuType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/View/SegmentedMenuView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/ViewModel/SegmentedMenuViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Schedule/View/AddScheduleView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Schedule/ViewModel/AddScheduleViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/ToDo/Model/Matrix.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/ToDo/View/AddToDoPrioritySheet.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/ToDo/View/AddToDoTextView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/ToDo/View/AddToDoToolbarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/ToDo/View/AddToDoView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/ToDo/ViewModel/AddToDoViewModel.swift
Labels: Feat, Refactor, 세민

#43 [Refactor] #37 - 앱의 인증/세션 관리 구조와 루트 전환 로직 리팩토링
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Resource/Launch Screen.storyboard
  Memento-iOS/Memento-iOS/Resource/Lottie/LottieView.swift
  Memento-iOS/Memento-iOS/Resource/Lottie/SplashScreenView.swift
  Memento-iOS/Memento-iOS/Resource/Lottie/memento_logo_animation.json
  Memento-iOS/Memento-iOS/Source/App/Memento_iOSApp.swift
  Memento-iOS/Memento-iOS/Source/Network/AI/PrioritizationAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/AI/TargetType/PrioritizationTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/AuthSession/AuthSession+Apple.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/AuthSession/AuthSession+Google.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/AuthSession/AuthSession+Network.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/AuthSession/AuthSession.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/BaseTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/NetworkService.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/Token/RefreshService.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/Token/TokenInterceptor.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/Token/TokenKeychainManager.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/TokenRefreshPlugin.swift
  Memento-iOS/Memento-iOS/Source/Network/Health/HealthCheckAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Health/HealthCheckTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/AppleSchedulesAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Request/AppleScheduleListRequest.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Request/UserInfoRequest.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/AppleSchedulesTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/MemberTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/TokenRefreshType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/UserInfoTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/LoginAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/MemberAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/UserInfoAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/UserUptimeAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/ScheduleAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/ScheduleTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Tag/TagAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Tag/TagTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/ToDoListAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/ToDoListTargetType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/CalendarConnectView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/LoginView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/SleepCycleSettingView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/WorkPreferenceView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/WorkSelectionView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/AppState.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/AuthViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: Chore, Feat, Refactor, 정욱

#49 [Feat] #47 - SettingView API 연결, 구조 수정
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/Alert/CustomAlertView.swift
  Memento-iOS/Memento-iOS/Source/Extension/Date+.swift
  Memento-iOS/Memento-iOS/Source/Extension/String+.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/UserInfoTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Setting/DTO/Request/UserTimezoneRequest.swift
  Memento-iOS/Memento-iOS/Source/Network/Setting/DTO/Request/UserUptimeRequest.swift
  Memento-iOS/Memento-iOS/Source/Network/Setting/UserInfoUpdateAPIService.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/View/SettingView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/View/TimeView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/ViewModel/SettingViewModel.swift
Labels: Chore, Feat, Network, 정욱
