Repository dev-memento/memento-iOS, pull requests merged in 2025-03, with the labels that each got.

#10 [Feat] #6 - 이중 바텀 시트 구현 및 리팩터링
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoTextView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/KeyboardToolbarItem.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/SegmentedMenu/View/SegmentedMenuView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/SegmentedMenu/ViewModel/SegmentedMenuViewModel.swift
Labels: Del, Feat, Refactor, 범수

#13 [Fix] #5 - ToDoList Completion 수정
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ToDoListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarItem.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarView.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/DTO/Response/ToDoListCompletedResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/DTO/Response/ToDoListResponseData.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/ToDoListViewModel.swift
Labels: Fix, Refactor, 세민

#18 [Feat] #15 - 일정 추가 뷰 바텀 시트 연결 및 시간 로직 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/Alert/ScheduleAlertView.swift
  Memento-iOS/Memento-iOS/Source/Component/Alert/ToDoAlertView.swift
  Memento-iOS/Memento-iOS/Source/Const/PresentationFraction.swift
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Extension/Date+.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/Model/DateTimeSelection.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/AddEventTitleView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/AddScheduleView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/AllDayCheckBoxButton.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/DateTimePickerSectionView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/DateTimePickerView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/ViewModel/AddEventTitleViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/ViewModel/AddSchedulePickerButtonViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/ViewModel/AddScheduleViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoHeaderView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoKeyboardToolbarItem.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoPriorityView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoTextView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Model/PickerButtonType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Model/SegmentedMenuType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Model/Tag.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Model/ViewType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/PickerButton/View/PickerButton.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/PickerButton/ViewModel/BasePickerViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Protocols/Presentable.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Protocols/TagSelectable.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Sheet/BaseSheetView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagListItem.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagPickerButton.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagPickerSheetView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/View/SegmentedMenuView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/View/SheetContainer.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/View/SheetOKButton.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/View/TagPickerSheet.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/ViewModel/SegmentedMenuViewModel.swift
  Memento-iOS/Memento-iOS/Source/Utils/DynamicPresentationDetent.swift
Labels: Chore, Del, Feat, Refactor, 범수

#22 [Feat] #19 - 브레인덤프 뷰 제거 및 자연어 입력 토글 버튼 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/AddScheduleView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/ViewModel/AddScheduleViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoHeaderView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/BrainDump/View/BrainDumpView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Model/SegmentedMenuType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/View/CustomToggleStyle.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/View/CustomToggleView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/View/SegmentedMenuView.swift
Labels: Chore, Feat, Refactor, 범수

#21 Fix/#20 - 토큰 만료로 인한 리프래쉬 토큰으로 토큰 갱신 처리 에러 해결
  Memento-iOS/Memento-iOS/Source/Network/Base/TokenRefreshPlugin.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Response /NewAccessTokenResponse.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/ToDoListAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Todo/TodoAPIService.swift
Labels: Fix, 정욱

#23 Feat/#16 Setting 관련 View 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Source/Component/CustomNavigationBar.swift
  Memento-iOS/Memento-iOS/Source/Component/RoundedCorner.swift
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/LoginView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/Model/TagItem.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/View/IntegrationsView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/View/SettingView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/View/TagEditDetailView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/View/TagEditView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/View/TimeView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Setting/ViewModel/SettingViewModel.swift
Labels: Feat, 정욱
